AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  grade-calc

  Sample SAM Template for grade-calc

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  GradeCalcQueue:
    Type: AWS::SQS::Queue
  GradeCalcDLQ:
    Type: AWS::SNS::Topic
  GradeCalcTopic:
    # create topic of type sns
    Type: AWS::SNS::Topic
  GradeCalcBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-${AWS::AccountId}-${AWS::Region}
        
  GradeCalcFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: grade_calc/
      Handler: grade_calc.lambda_handler
      Runtime: python3.9
      DeadLetterQueue: 
        Type: SNS
        TargetArn: !Ref GradeCalcDLQ
      Architectures:
        - x86_64
      Policies:
        - S3ReadPolicy: 
            BucketName: !Sub ${AWS::StackName}-${AWS::AccountId}-${AWS::Region}
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt GradeCalcTopic.TopicName
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref GradeCalcBucket
            Events: s3:ObjectCreated:*
      #  SNS related 
      Environment: 
        Variables:
          GRADE_CALC_TOPIC: !Ref GradeCalcTopic
    
  GradeReportFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: grade_calc/
      Handler: grade_report.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref GradeCalcTopic
  GradeLoopFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: grade_calc/
      Handler: grade_report_sqs.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt GradeCalcQueue.Arn
            BatchSize: 5
            
  ErrorHandlerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: grade_calc/
      Handler: error_handler.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref GradeCalcDLQ






